name: collective.clamav CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip install
        run: pip install -r requirements.txt -c constraints_plone52.txt
      - name: buildout
        run: buildout -t 10 -c test_plone52.cfg
      - name: Install ClamAV
        run: |
          sudo apt-get -y install clamav clamav-freshclam clamav-unofficial-sigs
          sudo freshclam
          sudo service clamav-daemon start
      - name: Install geckodriver
      - run: |
          wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
          tar xfz geckodriver-v0.24.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin
          DISPLAY=":99.0" Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
      - name: Run tests
        run: bin/test --all
